<a id='top'></a>

# CSCI 3022: Intro to Data Science - Spring 2020 Practicum 2
***

This practicum is due on Canvas by **11:59 PM on Friday May 1**. Your solutions to theoretical questions should be done in Markdown/MathJax directly below the associated question.  Your solutions to computational questions should include any specified Python code and results as well as written commentary on your conclusions.  

**Here are the rules:** 

1. All work, code and analysis, must be your own. 
1. You may use your course notes, posted lecture slides, textbooks, in-class notebooks, and homework solutions as resources.  You may also search online for answers to general knowledge questions like the form of a probability distribution function or how to perform a particular operation in Python/Pandas. 
1. This is meant to be like a coding portion of your midterm exam. So, the instructional team will be much less helpful than we typically are with homework. For example, we will not check answers, help debug your code, and so on.
1. If something is left open-ended, it is because we want to see how you approach the kinds of problems you will encounter in the wild, where it will not always be clear what sort of tests/methods should be applied. Feel free to ask clarifying questions though.
2. You may **NOT** post to message boards or other online resources asking for help.
3. You may **NOT** copy-paste solutions *from anywhere*.
4. You may **NOT** collaborate with classmates or anyone else.
5. In short, **your work must be your own**. It really is that simple.

Violation of the above rules will result in an immediate academic sanction (*at the very least*, you will receive a 0 on this practicum or an F in the course, depending on severity), and a trip to the Honor Code Council.

**By submitting this assignment, you agree to abide by the rules given above.**

***

**Name**: Chandler de Spirlet

***


**NOTES**: 

- You may not use late days on the practicums nor can you drop your practicum grades. 
- If you have a question for us, post it as a **PRIVATE** message on Piazza.  If we decide that the question is appropriate for the entire class, then we will add it to a Practicum clarifications thread. 
- Do **NOT** load or use any Python packages that are not available in Anaconda 3.6. 
- Some problems with code may be autograded.  If we provide a function API **do not** change it.  If we do not provide a function API then you're free to structure your code however you like. 
- Submit only this Jupyter notebook to Canvas.  Do not compress it using tar, rar, zip, etc. 
- This should go without saying, but... For any question that asks you to calculate something, you **must show all work to receive credit**. Sparse or nonexistent work will receive sparse or nonexistent credit.


---

In [1]:
from scipy import stats
from math import isnan
import numpy as np 
import statsmodels.api as sm
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from calendar import month_name, different_locale

<br>

---

### [50 points] Problem 1: Multiple Linear Regression to Explain House Hauntings

<img src="https://s-media-cache-ak0.pinimg.com/originals/09/72/01/09720128cff5de4d4af038cd3fcf7f69.jpg" style="width: 300px;"/>

In an effort to control the skyrocketing prices of real estate in the Colorado Front Range, Governor Polis implemented a cutting edge new intervention. This new program oversaw the introduction of ghosts back into their natural ecosystem, after the ghost population seriously dwindled in recent decades due to overhaunting. However, an unfortunate miscalculation has led to haunted houses becoming a very serious problem in Colorado. Modern problems require modern solutions, so Governor Polis has hired you and the famous hedgehog data scientist/part-time ghostbuster Amy to determine what features of a house may be used to best predict a `haunted` score, related to the probability that a house with the given features is haunted (higher $\leftrightarrow$ more likely to be haunted).

You decide to use multiple linear regression to understand and predict what factors lead to increased haunted house hazard. You collected a data set from Haunted Zillow, the lesser-known database of haunted house prices and attributes. The data cover a variety of potential features, and you'll find this data in the file `houses.csv`. 

**Response**: 

- $\texttt{haunted}$: a haunting score, related to the probability that a house with the given features is haunted (higher $\leftrightarrow$ more likely to be haunted)

**Features**: 

- $\texttt{age}$: age of the house, in years
- $\texttt{area}$: square footage of interior of house
- $\texttt{bathrooms}$: number of bathrooms
- $\texttt{distance metro}$: distance to the nearest major metropolitan area (in miles)
- $\texttt{distance cemetery}$: distance to the nearest cemetery (in miles)
- $\texttt{cats}$: the number of cats within a one-block radius of the house
- $\texttt{howls}$: the number of wolf howls heard on an average night in the house's neighborhood
- $\texttt{clouds}$: what percentage of the sky was covered by clouds (fraction, 0-1)
- $\texttt{precipitation}$: amount of precipitation in the past 72 hours (inches)
- $\texttt{misery index}$: an economic indicator for how miserable the average United States citizen is, based on the unemployment rate and the inflation rate. More [here](https://www.stuffyoushouldknow.com/podcasts/whats-the-misery-index.htm) and [here](https://en.wikipedia.org/wiki/Misery_index_(economics)). Higher values correspond to more miserable citizens.
- $\texttt{ice cream sold}$: the number of units of ice cream sold at the farmer's market the week the house was most recently sold

**Part A**: Read the data from `houses.csv` into a Pandas DataFrame.  Note that since we will be doing a multiple linear regression we will need all of the features, so you should drop any row in the DataFrame that is missing data. 

In [2]:
# Your code here.
df = pd.read_csv('houses.csv')
df.dropna(inplace=True)
df.head()

age    area  bathrooms  distance metro  distance cemetery  cats  howls  \
0  118.94  2113.0          4             7.1               3.23   7.0    3.0   
1   20.60  1773.0          2             7.4               4.19   5.0    5.0   
2  260.84  2511.0          3             7.0               3.38   2.0    0.0   
3  101.33  2000.0          2             7.9               4.05   6.0    8.0   
4   96.94  1476.0          1             7.5               5.75   4.0    1.0   

   clouds  precipitation  misery index  ice cream sold   haunted  
0    1.00           0.82         12.99           273.0  0.123131  
1    1.00           0.99         16.77           184.0 -0.200243  
2    1.00           1.17         16.49           141.0  0.258651  
3    0.13           0.92          8.28           146.0  0.147983  
4    1.00           1.73          5.90           178.0 -0.113756

**Part B**: Perform the appropriate statistical test at the $\alpha = 0.01$ significance level to determine if _at least one_ of the features is related to the the response $y$.  Clearly describe your methodology and show all computations in Python. 

In [6]:
features = ['age', 'area', 'bathrooms', 'distance metro', 'distance cemetery', 'cats', 'howls', 'clouds', 'precipitation', 'misery index', 'ice cream sold']

for f in features: 
    print("SLR for {} vs haunted".format(f))
    print("----------------------")
    bhat, ahat, rval, pval, stderr = stats.linregress(df[f], df["haunted"])
    print("intercept = {:.4f}".format(ahat))
    print("slope = {:.4f}".format(bhat))
    print("p-value = {}".format(pval))
    print("alpha of 0.01, z_crit = {}".format(stats.norm.ppf(0.01)))
    print("z >= z_a: {}".format(pval >= (stats.norm.ppf(0.01))))
    print("\n")

SLR for age vs haunted
----------------------
intercept = -0.1589
slope = 0.0019
p-value = 0.003684267428603103
alpha of 0.01, z_crit = -2.3263478740408408
z >= z_a: True


SLR for area vs haunted
----------------------
intercept = 0.2459
slope = -0.0001
p-value = 0.5895004468410892
alpha of 0.01, z_crit = -2.3263478740408408
z >= z_a: True


SLR for bathrooms vs haunted
----------------------
intercept = 0.0122
slope = 0.0408
p-value = 0.4473107506661014
alpha of 0.01, z_crit = -2.3263478740408408
z >= z_a: True


SLR for distance metro vs haunted
----------------------
intercept = 0.2514
slope = -0.0217
p-value = 0.722940161450198
alpha of 0.01, z_crit = -2.3263478740408408
z >= z_a: True


SLR for distance cemetery vs haunted
----------------------
intercept = 0.6402
slope = -0.1146
p-value = 2.8888803960089485e-17
alpha of 0.01, z_crit = -2.3263478740408408
z >= z_a: True


SLR for cats vs haunted
----------------------
intercept = -0.0591
slope = 0.0303
p-value = 0.116107192304879

**Part C**: Write a function `forward_select(df, resp_str, maxk)` that takes in the DataFrame, the name of the column corresponding to the response, and the maximum number of desired features, and returns a list of feature names corresponding to the `maxk` most important features via forward selection.  At each stage in forward selection you should add the feature whose inclusion in the model would result in the lowest sum of squared errors $(SSE)$. Use your function to determine the best $k=5$ features to include in the model. Clearly indicate which feature was added in each stage. 

**Note**: The point of this exercise is to see if you can implement **foward_select** yourself.  You may of course use canned routines like statmodels OLS, but you may not call any Python method that explicitly performs forward selection.

In [31]:
approved_features = []
features = ['age', 'area', 'bathrooms', 'distance metro', 'distance cemetery', 'cats', 'howls', 'clouds', 'precipitation', 'misery index', 'ice cream sold']
def forward_select(df, resp_str, maxk):
    for x in range(1, maxk + 1):
        forward_select_helper(df, 'haunted', x)
  
def forward_select_helper(df, resp_str, step):
    X = df[features]
    X = sm.add_constant(X)
    y = df[resp_str]
    model = sm.OLS(y, X).fit()
    diff = 999
    feature = ''
    idx = 0
    for item in model.params:
        if (abs(0 - item) < diff):
            diff = item
            feature = features[idx]
        idx += 1
    approved_features.append(feature)
    print('Adding {} at step {}'.format(feature, step))
    features.remove(feature)
    
forward_select(df, 'haunted', 5)
print('Features being used in the model: {}'.format(approved_features))

Adding bathrooms at step 1
Adding distance metro at step 2
Adding distance cemetery at step 3
Adding age at step 4
Adding area at step 5
Features being used in the model: ['bathrooms', 'distance metro', 'distance cemetery', 'age', 'area']


**Part D**: Write down the multiple linear regression model, including estimated parameters, obtained by your forward selection process. 

In [33]:
X = df[approved_features]
X = sm.add_constant(X) 
y = df["haunted"] 
model = sm.OLS(y, X).fit()
print(model.params)

const                0.693001
bathrooms           -0.015692
distance metro      -0.025540
distance cemetery   -0.109364
age                  0.001280
area                -0.000023
dtype: float64


$$
\texttt{haunted} = 0.693001 - 0.015692 \times \texttt{bathrooms} - 0.015692 \times \texttt{distance metro} - 0.109364 \times \texttt{distance cemetery} + 0.001280 \times \texttt{age} - 0.000023 \times \texttt{area}
$$

**Part E**: Perform the appropriate statistical test at the $\alpha = 0.05$ significance level to determine whether there is a statistically significant difference between the full model with all features and the reduced model obtained by forward selection in **Part D**. 

In [ ]:
# Your code here.

**Part F**: Based on your conclusions in **Part E**, use the _better_ of the two models to predict the haunted house hazard when the following features are observed: 

- $\texttt{age}$: 150 years
- $\texttt{area}$: 2200 square feet
- $\texttt{bathrooms}$: 3 bathrooms
- $\texttt{distance metro}$: 25 miles
- $\texttt{distance cemetery}$: 5 miles
- $\texttt{cats}$: 20 cats
- $\texttt{howls}$: 5 wolf howls/night
- $\texttt{clouds}$: 0.65 cloud cover
- $\texttt{precipitation}$: 0 inches
- $\texttt{misery index}$: 10
- $\texttt{ice cream sold}$: 125

In [38]:
haunted = 0.693001 - 0.015692 * 3 - 0.015692 * 25 - 0.109364 * 5 + 0.001280 * 150 - 0.000023 * 2200
print('The haunted value is {}'.format(haunted))

The haunted value is -0.15179500000000004


**Part G:** Governor Polis dabbles a bit in the art of data science, as well as the science of data art. He tells you that the response (`haunted` score) that you and Amy predicted is actually the natural logarithm of the _odds_ that a house with the given features is haunted, where if $p$ is the probability that a house is haunted, then the odds are given by $$\text{odds} = \dfrac{p}{1-p}$$

So using Govenor Polis's information and combining it with our knowledge of logistic regression, the probability of a house being haunted is:

$$p(\text{haunted} \mid x_1, x_2, \ldots) = \dfrac{1}{1+\texttt{exp}[-(\beta_0 + \beta_1x_1 + \ldots + \beta_p x_p)]}$$

Perform this computation, then use a decision threshold of 0.5 to classify the house from **Part F** as haunted or not haunted. No new models should be fit here; use the same model that you used in Part F.

In [41]:
from math import exp
exp_val = exp(-(haunted))
print('The value of p(haunted | x1, x2, ...) = {}'.format((1 / (1 + exp_val))))
print('We conclude that the house above is not haunted as the p(haunted | x1, x2, ...) is < 0.5')

The value of p(haunted | x1, x2, ...) = 0.46212394953806374
We conclude that the house above is not haunted as the p(haunted | x1, x2, ...) is < 0.5


<br>

---



### [50 points] Problem 2: Amazon Forest Fires
A non-profit trying to protect the amazon rain forest has recruited you to join their data science corps. For your first task, they've given you a dataset with the number of reported forest fires in each state in the Amazon region of Brazil during each month between 1998 and 2017. The Brazilian government has 500 extra wildland firefighters and they have asked your non-profit to determine which state or states they should allocate these firefighters to during each month of the year. To do this, they want you to calculate an 80% confidence interval for the mean and median number of fires that occur during each month for each state, and use those statistics to determine where the firefighters should be assigned.

#### Part A: Loading The CSV
Read the csv located in `amazon.csv` into a pandas data frame. Brazil and many other countries use the period (.) symbol as a thousands separator and a comma (,) as the decimal separator. Ex. One Thousand And $\frac{75}{100}$ would be represented as $1.000,75$ instead of the familiar english notation $1,000.75$. When you read it in, you'll need to use a period(.) as the thousands separator and a comma(,) as the decimal separator. Because the comma is already in use as the decimal separator, this file uses a different character to separate columns in the data. Open up the file in a text editor and figure out what character was used. Then find the correct arguments to `pd.read_csv` to read in this file properly. Look up the docs if you're unsure what the arguments you'll need are. Print out the `.info` summary of the dataframe after you've read it in.

In [53]:
amazon_fires = pd.read_csv('amazon.csv', sep=";")# Your code here.
amazon_fires.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   year    6453 non-null   object
 1   state   6452 non-null   object
 2   month   6454 non-null   object
 3   number  6448 non-null   object
 4   date    6450 non-null   object
dtypes: object(5)
memory usage: 252.2+ KB


#### Part B: Data Cleaning

This dataset isn't paticularly useful in it's current state, so we'll need to clean it up a bit. Some data scientists say that most of their job is to wrangle data, so this will give you a taste of cleaning a real world data set. Perform the following tasks. 
1. Drop the 'date' column. The only information this column holds is the year, which we already have in another column. Use the `.info` summary provided to check your work.
2. Drop any rows with null values in any of the remaining columns. Use the provided code to print the number of rows remaining after this step.
3. Print all the unique values of the 'month' column. You'll notice that one is encoded with a different character encoding then the format that pandas is using.
4. Convert the Portugese month names to English month names. If you'd like to use them, we've included the 'month_name' and the 'different_encoding' modules of the python calendar library. There are many ways to accomplish this task, and these modules are not required, but may make things easier. As part of this step, you should make sure that the Portugese month with the encoding problem is translated to the correct english month. Use the `.unique` method provided for you to check your work. 
5. Check the number column for any values that seem impossible. If you find any values you think are impossible, drop them. As a guidline, we would never expect a single state to have more than 50,000 reported forest fires in a single month. Also keep in mind that we are tracking forest fires here. Do negative or fractional forest fires really make sense? You should check for any obivously impossible conditions that you think might occur, and drop rows accordingly. Use the provided code to print the number of rows remaining after this step.
6. Since you're new on the job, some of your co-workers may have played a prank on you... Print out all the unique values of the 'year' column and drop any rows with values that don't make sense. Use the provided code to print the number of rows remaining after this step.
7. For every state in the data, print the number of rows the state has associated with it. A number of states have far more observations than the others. Each state should have roughly 240 observations (20 years multiplied by 12 months/year minus any bad data). Drop all the observations for any states that have more than 240 rows associated with them. For two points of extra credit, figure out why these states have way more rows associated with them than they should. If you choose to do the extra credit, put your answer in the markdown cell below. 
8. To give you an idea of whether your answer is correct, we've provided a unit test below the last cell. It should pass. If it doesn't, go back and figure out which step has gone awry.

We've given you a code cell for each task to make organizing the grading a bit easier. Please perform step 1 in the first code cell and so on.

**NOTE:** Since some of these tasks are not totally trivial, you may use any resources other than your classmates on this part of this problem. This means you may consult google, stack overflow, the python/pandas documentation, some random book on pandas you might have, etc... But you may not consult your classmates for help. We will also be more helpful on this problem in office hours and in response to your *private* piazza messages.  ***CITE ALL RESOURCES USED IN A CODE COMMENT. A URL OR A BOOK TITLE IS SUFFICIENT. ANY CODE OBIVOUSLY COPIED FROM OUTSIDE SOURCES WITH OUT A CITATION WILL EARN YOU NO CREDIT ON THIS PROBLEM.***

In [54]:
#Code for data cleaning task 1 here:
amazon_fires.drop('date', axis=1, inplace=True)
amazon_fires.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   year    6453 non-null   object
 1   state   6452 non-null   object
 2   month   6454 non-null   object
 3   number  6448 non-null   object
dtypes: object(4)
memory usage: 201.8+ KB


In [55]:
#Code for data cleaning task 2 here:
amazon_fires.replace('', np.nan, inplace=True)
amazon_fires.dropna(inplace=True)
print(amazon_fires.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6446 entries, 0 to 6453
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   year    6446 non-null   object
 1   state   6446 non-null   object
 2   month   6446 non-null   object
 3   number  6446 non-null   object
dtypes: object(4)
memory usage: 251.8+ KB
None


In [56]:
#Code for data cleaning task 3 here:
print(amazon_fires['month'].unique())

['Janeiro' 'Fevereiro' 'Mar�o' 'Abril' 'Maio' 'Junho' 'Julho' 'Agosto'
 'Setembro' 'Outubro' 'Novembro' 'Dezembro']


In [57]:
#Code for data cleaning task 4 here:
amazon_fires.reset_index(drop=True, inplace=True)
def get_int(month):
    if (month == 'Jan'):
        return 1
    if (month == 'Feb') or (month == 'Fev'):
        return 2
    if (month == 'Mar'):
        return 3
    if (month == 'Apr') or (month == "Abr"):
        return 4
    if (month == 'May') or (month == 'Mai'):
        return 5
    if (month == 'Jun'):
        return 6
    if (month == 'Jul'):
        return 7
    if (month == 'Aug') or (month == 'Ago'):
        return 8
    if (month == 'Sep') or (month == 'Set'):
        return 9
    if (month == 'Oct') or (month == 'Out'):
        return 10
    if (month == 'Nov'):
        return 11
    if (month == 'Dec') or (month == 'Dez'): 
        return 12
    else:
        return 100
#amazon_fires.drop(amazon_fires.index[2976], inplace=True)
for x in range(0, len(amazon_fires)):
    with different_locale('en_US'):
        temp = amazon_fires['month'][x][0:3]
        s = month_name[get_int(temp)]
        amazon_fires['month'].replace(
            to_replace= amazon_fires['month'][x],
            value=s,
            inplace=True
        )  
print(amazon_fires['month'].unique())

['January' 'February' 'March' 'April' 'May' 'June' 'July' 'August'
 'September' 'October' 'November' 'December']


In [58]:
#Code for data cleaning task 5
import re
from decimal import Decimal
amazon_fires.reset_index(drop=True, inplace=True)
idx = 0
for x in amazon_fires['number']:
    temp = str(x).replace('.','').replace(',','.')
    temp_1 = Decimal(float(temp))
    amazon_fires['number'].replace(
        to_replace=x,
        value = temp_1,
        inplace=True
    )
    num = temp_1
    if ((num > 15000) or (num < 0)):
        amazon_fires.drop(amazon_fires.index[idx], inplace=True)
    if (idx < len(amazon_fires['number'])):
        idx += 1
    else:
        break
        
amazon_fires.reset_index(drop=True, inplace=True)
    
print(amazon_fires['number'].unique())
print(len(amazon_fires))

[Decimal('0') Decimal('10') Decimal('12') ... Decimal('2032')
 Decimal('833') Decimal('623')]
6433


In [59]:
#Code for data cleaning task 6
amazon_fires.reset_index(drop=True, inplace=True)
idx = 0
for x in amazon_fires['year']:
    temp_match = re.search("^[0-9]+$", str(x))
    if (temp_match == None):
        amazon_fires.drop(amazon_fires.index[idx], inplace=True)
    if (idx < len(amazon_fires['year'])):
        idx += 1
    else: 
        break
amazon_fires.reset_index(drop=True, inplace=True)
print(len(amazon_fires))

6429


In [60]:
#Code for data cleaning task 7
amazon_fires.head()
states = {}
amazon_fires.reset_index(drop=True, inplace=True)
idx = 0
for x in amazon_fires['state']:
    name = x
    if (name == 'Mato Grosso' or name == 'Paraiba' or name == 'Rio'):
        amazon_fires.drop(amazon_fires.index[idx], inplace=True)
    else:
        if (name not in states.keys()):
            states[name] = 1
        else:
            if (states[name] >= 240):
                amazon_fires.drop(amazon_fires.index[idx], inplace=True)
            else:
                states[name] += 1   
        if (idx < len(amazon_fires['state'])):
            idx += 1
        else:
            break
amazon_fires.reset_index(drop=True, inplace=True)
print(len(amazon_fires))

4772


In [61]:
#Given Test. This Cell Should Not Throw an Exception!
assert \
    len(amazon_fires['state'].unique()) == 20 and \
    list(amazon_fires['month'].unique()) == \
        ['January', 'February', 'March', 'April', 'May', 'June',
             'July', 'August','September', 'October', 'November',
             'December'] and \
    len(amazon_fires) == 4772, 'somethings wrong in problem 1.'

#### Part C: Medians and Means!
In this part of the problem, we'll calculate an 80% confidence interval for both the mean and median number of wildfires each state has during each month of the year. 

For the mean you should use the appropriate confidence interval with the correct distribution. Remember to check how many observations we have. Use the sample standard deviation. 

For the median, we'll have to bootstrap it because the median is not known to be normally distributed. You should bootstrap 1000 samples of the same length as the original sample for each month for each state. Calculate the median for each bootstrapped sample. Then take the middle 80% of the bootstrapped medians as your confidnce interval. This is called a bootstrapped percentile median. There are a few more complex and slightly more rigourous ways to estimate the median from bootstrapped samples, but this will serve for our purposes.

You're given a dictionary of dictionaries to store your confidence intervals for the medians and means in. 

Take a look at the dictionary structure below. 

The idea here is that for every month, for every state, you will fill in the `mean_CI` with a length two list that contains the low and high end of the confidence interval for the true mean number of fires for that state in that month. 

Similiarly, for every month, for every state, you will fill in the `median_CI` with a length two list that contains the low and high end of the confidence interval for the true median number of fires for that state in that month.

For example:

When you're done `months['January']['Acre']['mean_CI']` should be a list with the low and high bounds for the confidence interval of the true mean number of wildfires in the state of Acre in January. So `months['January']['Acre']['mean_CI'][0]` should be the low end of the CI for the mean, and `months['January']['Acre']['mean_CI'][1]` should be the high end of the CI for the mean.

`months['January']['Acre']['median_CI']` should hold the confidence interval for the true median number of wildfires in the state of Acre in January. So `months['January']['Acre']['median_CI'][0]` should be the low end of the CI for the median, and `months['January']['Acre']['median_CI'][1]` should be the high end of the CI for the median.

In [62]:
#GIVEN CODE DO NOT CHANGE THIS!!!
#YOU SHOULD BE WRITING CODE IN THE NEXT CELL(s) THAT FILLS IN THE 'months' DICTIONARY.

#If you're curious what copy and deep copy do and why we used them here see an explanation 
#here: https://thispointer.com/python-how-to-copy-a-dictionary-shallow-copy-vs-deep-copy/

from copy import deepcopy

mean_median_dict ={
    'mean_CI' : None,
    'median_CI': None
}

CI_median_num_fires = {
    'Acre': dict(mean_median_dict),
    'Alagoas':dict( mean_median_dict),
    'Amapa':dict( mean_median_dict),
    'Amazonas':dict( mean_median_dict),
    'Bahia':dict( mean_median_dict),
    'Ceara':dict( mean_median_dict),
    'Distrito Federal':dict( mean_median_dict),
    'Espirito Santo':dict( mean_median_dict),
    'Goias':dict( mean_median_dict),
    'Maranhao':dict( mean_median_dict),
    'Minas Gerais':dict( mean_median_dict),
    'Para':dict( mean_median_dict),
    'Pernambuco':dict( mean_median_dict),
    'Piau':dict( mean_median_dict),
    'Rondonia':dict( mean_median_dict),
    'Roraima':dict( mean_median_dict),
    'Santa Catarina':dict( mean_median_dict),
    'Sao Paulo':dict( mean_median_dict),
    'Sergipe':dict( mean_median_dict),
    'Tocantins':dict( mean_median_dict)  
}

months = {
    'January': deepcopy(CI_median_num_fires),
    'February': deepcopy(CI_median_num_fires),
    'March': deepcopy(CI_median_num_fires), 
    'April': deepcopy(CI_median_num_fires), 
    'May': deepcopy(CI_median_num_fires),
    'June': deepcopy(CI_median_num_fires),
    'July': deepcopy(CI_median_num_fires),
    'August': deepcopy(CI_median_num_fires), 
    'September': deepcopy(CI_median_num_fires), 
    'October': deepcopy(CI_median_num_fires),
    'November': deepcopy(CI_median_num_fires),
    'December': deepcopy(CI_median_num_fires)
}

In [76]:
#Your code here:
#Your code should modify the 'months' dictionary provided to add the CIs. 

def mean_CI(arr):
    n=len(arr)
    xbar=np.sum(arr)/n
    svar=np.sum((xi-xbar)**2/(n-1) for xi in arr)
    sd=np.sqrt(svar)
    a, b = stats.norm.interval(.80, loc=xbar, scale=sd/np.sqrt(n))
    return [a, b]

def median_boot(arr):
    b = np.array([np.mean(np.random.choice(arr, replace=True, size=len(arr))) for ii in range(1000)])
    L, U = np.percentile(b, 10), np.percentile(b, 90)
    CI = np.array([L, U])
    return CI

#months['January']['Acre']['median_CI'][1]
dfJan = amazon_fires.loc[amazon_fires["month"]=='January'].copy()
dfFeb = amazon_fires.loc[amazon_fires["month"]=='February'].copy()
dfMar = amazon_fires.loc[amazon_fires["month"]=='March'].copy()
dfApr = amazon_fires.loc[amazon_fires["month"]=='April'].copy()
dfMay = amazon_fires.loc[amazon_fires["month"]=='May'].copy()
dfJun = amazon_fires.loc[amazon_fires["month"]=='June'].copy()
dfJul = amazon_fires.loc[amazon_fires["month"]=='July'].copy()
dfAug = amazon_fires.loc[amazon_fires["month"]=='August'].copy()
dfSep = amazon_fires.loc[amazon_fires["month"]=='September'].copy()
dfOct = amazon_fires.loc[amazon_fires["month"]=='October'].copy()
dfNov = amazon_fires.loc[amazon_fires["month"]=='November'].copy()
dfDec = amazon_fires.loc[amazon_fires["month"]=='December'].copy()
df_s = [dfJan, dfFeb, dfMar, dfApr, dfMay, dfJun, dfJul, dfAug, dfSep, dfOct, dfNov, dfDec]
[df.reset_index(inplace=True) for df in df_s]

def populate_dict(df, month_name):
    currentState = df['state'][0]
    stateNums = []
    idx = 0
    for state_name in df['state']:
        if (idx < len(df['state'])):
            if (state_name == currentState):
                stateNums.append(float(df['number'][idx]))
            if (state_name != currentState):
                months[month_name][df['state'][idx - 1]]['mean_CI'] = mean_CI(stateNums)
                medians = median_boot(stateNums)
                months[month_name][df['state'][idx - 1]]['median_CI'] = [medians[0], medians[1]]
                stateNums = []
                stateNums.append(float(df['number'][idx]))
                currentState = state_name
        if (idx == len(df['state']) - 1):
            months[month_name][df['state'][idx - 1]]['mean_CI'] = mean_CI(stateNums)
            medians = median_boot(stateNums)
            months[month_name][df['state'][idx - 1]]['median_CI'] = [medians[0], medians[1]]
            break
        idx += 1  
        
populate_dict(dfJan, 'January')
populate_dict(dfFeb, 'February')
populate_dict(dfMar, 'March')
populate_dict(dfApr, 'April')
populate_dict(dfMay, 'May')
populate_dict(dfJun, 'June')
populate_dict(dfJul, 'July')
populate_dict(dfAug, 'August')
populate_dict(dfSep, 'September')
populate_dict(dfOct, 'October')
populate_dict(dfNov, 'November')
populate_dict(dfDec, 'December')

/Users/chandlerdespirlet/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  import sys


In [77]:
#DONT CHANGE THIS. WE USE IT TO MAKE THE OUTPUT LEGIBLE FOR GRADING
import pprint
pp = pprint.PrettyPrinter(indent=1)
pp.pprint(months)

{'April': {'Acre': {'mean_CI': [0.8079245430501509, 3.2920754569498487],
                    'median_CI': [0.95, 3.2]},
           'Alagoas': {'mean_CI': [8.12772239540053, 16.372277604599468],
                       'median_CI': [8.395000000000001, 16.45]},
           'Amapa': {'mean_CI': [0.35197671306401546, 0.9480232869359846],
                     'median_CI': [0.3, 0.9]},
           'Amazonas': {'mean_CI': [7.065043195403443, 12.134956804596555],
                        'median_CI': [7.295, 12.15]},
           'Bahia': {'mean_CI': [94.99540288280348, 156.0045971171965],
                     'median_CI': [96.49000000000001, 156.925]},
           'Ceara': {'mean_CI': [2.7334352413528853, 4.866564758647114],
                     'median_CI': [2.8, 4.9]},
           'Distrito Federal': {'mean_CI': [0.648360010452139,
                                            1.851639989547861],
                                'median_CI': [0.75, 1.85]},
           'Espirito Santo': {'mean_CI': [7.5

In [78]:
#Given Test for the mean confidence intervals

rounded_mean_CI = [round(x, 2) for x in months['April']['Acre']['mean_CI']]
assert rounded_mean_CI == [0.76, 3.34], 'somethings wrong in the mean'

AssertionError: somethings wrong in the mean

In [79]:
#Given test for the median confidence intervals. 
#Your code is probably correct if it passes this test, but since bootstrapping the medain is a stochastic process
#you may have this test fail. If it fails, run it a few times. 
#If it continues to fail, your code is probably incorrect.

low_median_CI = months['April']['Acre']['median_CI'][0]
high_median_CI = months['April']['Acre']['median_CI'][1]
assert -1 <= low_median_CI <= 1 and 0 <= high_median_CI <= 3, 'somethings wrong in the median'

AssertionError: somethings wrong in the median

#### Part E: Where Do The Firefighters Go?
Now, we'll determine which state the Brazilian government should assign it's fire fighters to. For each month of the year, you should perform the folllowing selection process:
1. Find the state with the highest CI for the median for this month (it's easiest and ok to just use the upper bound here). 
2. Find any states that have a median CI that overlaps with the highest CI foud in step 1. If no states overlap with the highest CI found in step 1, then use that stat. 
3. If overlapping confidence intervals are found on the median, we'll use the CI for the mean to break ties.
4. Out of the states with overlapping CIs for median (every state in part 3), find the state with the highest mean CI. 
5. Determine if any of the states from part 3 have a mean CI that overlaps with the state found in step 4. 
6. If no state overlap with the state found in part 4, then just use that state. If other states have overlapping mean CIs too, then we'll split up the firefighters and assign some of them to every state that has both an overlapping median and mean CI with the state that has the highest median CI.

Once you've used the selection process above, use a markdown table to display a list of each state that recieves  some of the firefighters for each month.